/**
 * Sprint J — Final Realistic Marketplace Data.
 *
 * Adds exactly 3 hand-authored, materially non-clone, fully tri-lingual
 * (EN/HY/RU) listings to every one of the 9 public categories (27 total),
 * each owned by one of 8 fresh demo partners. Deliberately self-contained:
 * unlike `seedDemoInventoryScenarios.js`/`seedDemoListingRichContent.js`
 * (which build on the dev-vendor partner `seedAll()` already creates),
 * this module has NO dependency on `seedDemoMarketplace.js` or either of
 * those two files — it only needs the plain `seedAll()` baseline
 * (categories/listing_types/bookable_unit_types/pricing_models/cities/
 * amenities/policy_definitions/currencies/languages), so it can be
 * exercised on its own by a focused, fast integration test instead of
 * paying for the full ~80-listing/150-booking demo pipeline every run.
 *
 * Root cause this addresses: before Sprint J, `seedAll()` seeds zero
 * marketplace listings, and the only listing-bearing seed layer
 * (`seedDemoMarketplace.js`) covers just 5 of the 9 categories with
 * titles generated by interpolating one shared description template with
 * an adjective+city pair — real city variety, but not materially
 * different businesses, and English-only. This module is what a category
 * page actually needs to look and read like a real, launch-ready
 * marketplace category.
 *
 * Reuses this `demo/` family's own established primitives rather than
 * re-implementing them (CLAUDE.md "never duplicate functionality"):
 * `insertListing`/`insertBookableUnit`/`seedCalendarWindow` from
 * `seedDemoInventoryScenarios.js`, and `upsertTranslation`/
 * `insertPolicyValue` from `seedDemoListingRichContent.js`.
 * Like both of those, every write here is a plain INSERT (safe because
 * this only ever runs — via `cli/seedDemo.js`/`cli/seedDemoDev.js` or a
 * test's own `up()+seedAll()` — against a just-recreated database).
 *
 * No dynamic attribute values (`listing_attribute_values_*`) are written
 * — those are optional, category-scoped Generic Attribute Engine detail,
 * not part of Sprint J's required "meaningful listing" checklist (title,
 * description, location, pricing, availability, amenities, policies,
 * media, published state — CLAUDE.md Sprint J spec §7). Phase 18 rich
 * content (highlights/itinerary/FAQs) is likewise intentionally not
 * authored here for all 27 — that tier already exists for the 6
 * `seedDemoInventoryScenarios.js` flagships, and duplicating that depth
 * across 27 more listings would be exactly the "inflate content beyond
 * what's needed" Sprint J's own spec (§31, §51) warns against.
 */

import argon2 from 'argon2';
import { getIdByCode, getIdsByCode } from '../helpers.js';
import {
  insertListing,
  insertBookableUnit,
  seedCalendarWindow,
} from './seedDemoInventoryScenarios.js';
import {
  upsertTranslation,
  insertPolicyValue,
} from './seedDemoListingRichContent.js';

// Shared by every Sprint J partner-owner account — same disposable-DB-only
// convention as `seedDemoMarketplace.js`'s own `DEMO_PASSWORD`.
const DEMO_PASSWORD = 'DemoPass!2024';

// ---------------------------------------------------------------------
// Partners — one per vertical, except Villas+Guest Houses (both PROPERTY,
// both naturally under one small property-management operator — CLAUDE.md
// Sprint J spec §24: "A company may own multiple logically related
// listings"). Slugs/emails/names are all distinct from the pre-existing
// `seedDemoMarketplace.js` partners (ararat-grand-hotels etc.) so the two
// layers never collide when both are seeded together.
// ---------------------------------------------------------------------
const PARTNERS = {
  hotels: {
    slug: 'zangezur-hotel-collection',
    legalName: 'Zangezur Hotel Collection LLC',
    displayName: 'Zangezur Hotel Collection',
    email: 'partner.zangezur-hotels@example.com',
    translations: {
      en: 'An independent hotel group running small, city- and region-specific hotels across Armenia.',
      hy: 'Անկախ հյուրանոցային խումբ, որը կառավարում է փոքր, տարբեր քաղաքների և տարածաշրջանների հյուրանոցներ ողջ Հայաստանում։',
      ru: 'Независимая гостиничная группа, управляющая небольшими отелями в разных городах и регионах Армении.',
    },
  },
  apartments: {
    slug: 'yerevan-urban-stays',
    legalName: 'Yerevan Urban Stays LLC',
    displayName: 'Yerevan Urban Stays',
    email: 'partner.yerevan-urban-stays@example.com',
    translations: {
      en: 'A short-term rental operator managing furnished apartments across central Yerevan.',
      hy: 'Կարճաժամկետ վարձակալության օպերատոր, որը կառավարում է կահավորված բնակարաններ Երևանի կենտրոնական մասերում։',
      ru: 'Оператор краткосрочной аренды, управляющий меблированными квартирами в центральных районах Еревана.',
    },
  },
  properties: {
    slug: 'armenian-highland-retreats',
    legalName: 'Armenian Highland Retreats LLC',
    displayName: 'Armenian Highland Retreats',
    email: 'partner.highland-retreats@example.com',
    translations: {
      en: 'A property-management company representing owner villas and guesthouses across Armenia’s lake, forest, and heritage regions.',
      hy: 'Անշարժ գույքի կառավարման ընկերություն, որը ներկայացնում է սեփականատիրական վիլլաներ և հյուրատներ Հայաստանի լճափնյա, անտառային և պատմական տարածքներում։',
      ru: 'Компания по управлению недвижимостью, представляющая виллы и гостевые дома частных владельцев в озёрных, лесных и исторических регионах Армении.',
    },
  },
  restaurants: {
    slug: 'yerevan-taste-collective',
    legalName: 'Yerevan Taste Collective LLC',
    displayName: 'Yerevan Taste Collective',
    email: 'partner.taste-collective@example.com',
    translations: {
      en: 'A small restaurant group behind a handful of distinct Armenian dining concepts.',
      hy: 'Փոքր ռեստորանային խումբ, որի հետևում կանգնած են մի քանի յուրահատուկ հայկական խոհանոցի հայեցակարգեր։',
      ru: 'Небольшая ресторанная группа, стоящая за несколькими самобытными концепциями армянской кухни.',
    },
  },
  tours: {
    slug: 'trans-caucasus-journeys',
    legalName: 'Trans-Caucasus Journeys LLC',
    displayName: 'Trans-Caucasus Journeys',
    email: 'partner.transcaucasus-journeys@example.com',
    translations: {
      en: 'A licensed tour operator running small-group day trips across Armenia.',
      hy: 'Լիցենզավորված տուրօպերատոր, որը կազմակերպում է փոքր խմբերով մեկօրյա ճամփորդություններ ողջ Հայաստանում։',
      ru: 'Лицензированный туроператор, организующий однодневные поездки для небольших групп по всей Армении.',
    },
  },
  carRentals: {
    slug: 'ararat-motor-rentals',
    legalName: 'Ararat Motor Rentals LLC',
    displayName: 'Ararat Motor Rentals',
    email: 'partner.ararat-motors@example.com',
    translations: {
      en: 'A locally operated car rental fleet serving travelers out of Yerevan.',
      hy: 'Տեղական ավտովարձույթի ավտոպարկ, որը սպասարկում է ճամփորդներին Երևանից։',
      ru: 'Местная компания по аренде автомобилей, обслуживающая путешественников из Еревана.',
    },
  },
  attractions: {
    slug: 'armenia-discovery-guides',
    legalName: 'Armenia Discovery Guides LLC',
    displayName: 'Armenia Discovery Guides',
    email: 'partner.discovery-guides@example.com',
    translations: {
      en: 'A guiding collective running cultural and outdoor excursions with licensed local guides.',
      hy: 'Ուղեկցորդների խումբ, որը լիցենզավորված տեղական ուղեկցորդների հետ կազմակերպում է մշակութային և բացօթյա էքսկուրսիաներ։',
      ru: 'Объединение гидов, проводящее культурные и активные экскурсии с лицензированными местными гидами.',
    },
  },
  entertainment: {
    slug: 'yerevan-after-hours',
    legalName: 'Yerevan After Hours LLC',
    displayName: 'Yerevan After Hours',
    email: 'partner.after-hours@example.com',
    translations: {
      en: 'An entertainment-venue operator running a small set of activity-based venues in Armenia.',
      hy: 'Ժամանցային օբյեկտների օպերատոր, որը կառավարում է մի քանի ակտիվությամբ հագեցած վայրեր Հայաստանում։',
      ru: 'Оператор развлекательных заведений, управляющий несколькими площадками с активным досугом в Армении.',
    },
  },
};

// ---------------------------------------------------------------------
// Listings — 3 per category, 27 total. Every `slug` is prefixed
// `sprintj-` so it can never collide with any pre-existing demo slug.
// ---------------------------------------------------------------------
const LISTINGS = [
  // === HOTELS (Zangezur Hotel Collection) ================================
  {
    partner: 'hotels',
    listingType: 'HOTEL',
    categorySlug: 'hotels',
    citySlug: 'gyumri',
    slug: 'sprintj-gyumri-heritage-hotel',
    pricingModel: 'PER_NIGHT',
    amount: 16000,
    images: ['hotels-6.svg', 'hotels-7.svg'],
    translations: {
      en: {
        title: 'Gyumri Heritage Hotel',
        summary:
          'A restored 19th-century black-tuff townhouse turned boutique hotel in Gyumri’s old quarter.',
        description:
          'Gyumri Heritage Hotel occupies a restored merchant’s house built from the black volcanic tuff the city is known for, a short walk from Vartanants Square. Rooms keep the original high ceilings and shuttered windows, furnished simply and warmly. A ground-floor breakfast room looks onto a small courtyard garden. The front desk can arrange a walking guide to the surrounding 19th-century streets.',
      },
      hy: {
        title: 'Գյումրի Հերիտաժ Հյուրանոց',
        summary:
          'XIX դարի սև տուֆից կառուցված վերականգնված առևտրական տուն-հյուրանոց Գյումրու հին թաղամասում։',
        description:
          'Գյումրի Հերիտաժ Հյուրանոցը տեղակայված է քաղաքի հայտնի սև տուֆից կառուցված վերականգնված առևտրական տան մեջ՝ Վարդանանց հրապարակից մի քանի րոպե հեռավորության վրա։ Սենյակները պահպանել են բարձր առաստաղներն ու փեղկավոր պատուհանները՝ կահավորված պարզ ու հարմարավետ ոճով։ Ներքևի հարկում գտնվող նախաճաշի սենյակը բացվում է փոքրիկ բակային այգու վրա։ Ընդունարանը կարող է կազմակերպել քայլարշավ շրջակա XIX դարի փողոցներով։',
      },
      ru: {
        title: 'Отель Gyumri Heritage',
        summary:
          'Восстановленный купеческий дом XIX века из чёрного туфа, превращённый в бутик-отель в старом квартале Гюмри.',
        description:
          'Отель Gyumri Heritage расположен в восстановленном купеческом доме из чёрного вулканического туфа, которым славится город, в нескольких минутах ходьбы от площади Вардананц. В номерах сохранены высокие потолки и ставни на окнах, обстановка простая и тёплая. Завтрак подаётся на первом этаже с видом на небольшой дворовый сад. Стойка регистрации может организовать пешую экскурсию по окрестным улицам XIX века.',
      },
    },
    amenities: ['WiFi', 'Parking', 'Breakfast Included', 'Non-Smoking Rooms'],
    policies: [
      { code: 'pets_allowed', value: 'false' },
      { code: 'smoking_allowed', value: 'false' },
      { code: 'children_allowed', value: 'true' },
      { code: 'cancellation_policy', value: 'MODERATE' },
      { code: 'check_in_time', value: '14:00' },
      { code: 'check_out_time', value: '11:00' },
    ],
    units: [
      {
        type: 'HOTEL_ROOM',
        label: 'Standard Room',
        capacity: 4,
        maxGuests: 2,
        basePriceAmount: 16000,
      },
    ],
  },
  {
    partner: 'hotels',
    listingType: 'HOTEL',
    categorySlug: 'hotels',
    citySlug: 'jermuk',
    slug: 'sprintj-jermuk-spa-resort-hotel',
    pricingModel: 'PER_NIGHT',
    amount: 38000,
    images: ['hotels-8.svg', 'hotels-1.svg'],
    translations: {
      en: {
        title: 'Jermuk Spa Resort Hotel',
        summary:
          'A mineral-spring spa resort hotel in Jermuk with an indoor thermal pool and treatment rooms.',
        description:
          'Jermuk Spa Resort Hotel draws on the town’s natural mineral springs, piping heated spring water into an indoor pool and a small treatment wing offering massage and mud-wrap sessions. Rooms are larger than a typical city hotel, most with a balcony facing the surrounding hills. The restaurant serves a spa-friendly menu alongside standard Armenian dishes. A short walk leads to the Jermuk waterfall.',
      },
      hy: {
        title: 'Ջերմուկ Սպա Հանգստյան Հյուրանոց',
        summary:
          'Հանքային ջրերով սպա հանգստյան հյուրանոց Ջերմուկում՝ փակ թերմալ լողավազանով և պրոցեդուրային սենյակներով։',
        description:
          'Ջերմուկ Սպա Հանգստյան Հյուրանոցը օգտագործում է քաղաքի բնական հանքային ջրերը՝ տաքացված աղբյուրի ջուրը մղելով փակ լողավազան և փոքր պրոցեդուրային թևամաս, որտեղ առաջարկվում են մերսում և տիղմային փաթաթումներ։ Սենյակներն ավելի ընդարձակ են, քան սովորական քաղաքային հյուրանոցում, մեծ մասը՝ պատշգամբով, որը նայում է շրջակա բլուրներին։ Ռեստորանն առաջարկում է սպային հարմար ուտեստներ՝ ավանդական հայկական ճաշատեսակների կողքին։ Կարճ քայլքով կարելի է հասնել Ջերմուկի ջրվեժ։',
      },
      ru: {
        title: 'Спа-отель Jermuk Spa Resort',
        summary:
          'Спа-отель на минеральных источниках в Джермуке с крытым термальным бассейном и процедурным крылом.',
        description:
          'Отель Jermuk Spa Resort использует природные минеральные источники города, подавая подогретую воду в крытый бассейн и небольшое процедурное крыло с массажем и грязевыми обёртываниями. Номера просторнее, чем в типичном городском отеле, у большинства есть балкон с видом на окрестные холмы. Ресторан предлагает щадящее спа-меню наряду с традиционными армянскими блюдами. Короткая прогулка ведёт к водопаду Джермук.',
      },
    },
    amenities: [
      'WiFi',
      'Parking',
      'Pool',
      'Air Conditioning',
      'Gym',
      'Non-Smoking Rooms',
    ],
    policies: [
      { code: 'pets_allowed', value: 'false' },
      { code: 'smoking_allowed', value: 'false' },
      { code: 'children_allowed', value: 'true' },
      { code: 'cancellation_policy', value: 'FLEXIBLE' },
      { code: 'check_in_time', value: '15:00' },
      { code: 'check_out_time', value: '12:00' },
    ],
    units: [
      {
        type: 'HOTEL_ROOM',
        label: 'Spa Balcony Room',
        capacity: 3,
        maxGuests: 3,
        basePriceAmount: 38000,
      },
    ],
  },
  {
    partner: 'hotels',
    listingType: 'HOTEL',
    categorySlug: 'hotels',
    citySlug: 'vanadzor',
    slug: 'sprintj-vanadzor-central-hotel',
    pricingModel: 'PER_NIGHT',
    amount: 13000,
    images: ['hotels-2.svg', 'hotels-3.svg'],
    translations: {
      en: {
        title: 'Vanadzor Central Hotel',
        summary:
          'A practical, no-frills business hotel two blocks from Vanadzor’s central square.',
        description:
          'Vanadzor Central Hotel is built for travelers passing through Lori province on business or on the way to the Debed Canyon monasteries: reliable WiFi, a 24-hour front desk, and a simple breakfast, without resort-style extras or pricing. Rooms are compact and clean, most facing the quiet side street rather than the main road. Parking is available directly behind the building.',
      },
      hy: {
        title: 'Վանաձոր Սենտրալ Հյուրանոց',
        summary:
          'Գործնական, պարզ բիզնես հյուրանոց՝ Վանաձորի կենտրոնական հրապարակից երկու փողոց հեռավորության վրա։',
        description:
          'Վանաձոր Սենտրալ Հյուրանոցը նախատեսված է Լոռու մարզով բիզնես նպատակով անցնող կամ Դեբեդի կիրճի վանքեր ուղևորվող ճամփորդների համար՝ հուսալի WiFi-ով, շուրջօրյա ընդունարանով և պարզ նախաճաշով, առանց հանգստյան համալիրին բնորոշ լրացուցիչների ու գների։ Սենյակները կոմպակտ են և մաքուր, մեծ մասը նայում է հանգիստ կողքի փողոցին, ոչ թե գլխավոր ճանապարհին։ Կայանատեղին հասանելի է անմիջապես շենքի հետևում։',
      },
      ru: {
        title: 'Отель Vanadzor Central',
        summary:
          'Практичный, без излишеств бизнес-отель в двух кварталах от центральной площади Ванадзора.',
        description:
          'Отель Vanadzor Central рассчитан на путешественников, проезжающих через провинцию Лори по делам или направляющихся к монастырям Дебедского каньона: надёжный WiFi, круглосуточная стойка регистрации и простой завтрак — без курортных дополнений и соответствующих цен. Номера компактные и чистые, большинство окнами на тихую боковую улицу, а не на главную дорогу. Парковка доступна прямо за зданием.',
      },
    },
    amenities: ['WiFi', 'Parking', 'Non-Smoking Rooms'],
    policies: [
      { code: 'pets_allowed', value: 'false' },
      { code: 'smoking_allowed', value: 'false' },
      { code: 'children_allowed', value: 'true' },
      { code: 'cancellation_policy', value: 'STRICT' },
      { code: 'check_in_time', value: '13:00' },
      { code: 'check_out_time', value: '11:00' },
    ],
    units: [
      {
        type: 'HOTEL_ROOM',
        label: 'Standard Room',
        capacity: 5,
        maxGuests: 2,
        basePriceAmount: 13000,
      },
    ],
  },

  // === APARTMENTS (Yerevan Urban Stays) ===================================
  {
    partner: 'apartments',
    listingType: 'PROPERTY',
    categorySlug: 'apartments',
    citySlug: 'yerevan',
    slug: 'sprintj-cascade-view-studio',
    pricingModel: 'PER_NIGHT',
    amount: 14000,
    images: ['apartments-1.svg', 'apartments-2.svg'],
    translations: {
      en: {
        title: 'Cascade View Studio',
        summary:
          'A compact studio two blocks from the Cascade, best suited to a solo traveler or couple.',
        description:
          'Cascade View Studio is a single open room with a kitchenette tucked along one wall, a queen bed, and a small balcony that catches a partial view of the Cascade complex’s upper terraces. It suits one or two guests who want to walk to the Cascade steps, Cafesjian Center, and Opera Square rather than drive. There’s no elevator, so it’s a third-floor walk-up.',
      },
      hy: {
        title: 'Կասկադ Վյու Ստուդիա',
        summary:
          'Կոմպակտ ստուդիա Կասկադից երկու փողոց հեռավորության վրա՝ լավագույնս հարմար մեկ ուղևորի կամ զույգի համար։',
        description:
          'Կասկադ Վյու Ստուդիան մեկ բաց սենյակ է՝ պատի երկայնքով տեղադրված փոքրիկ խոհանոցով, queen չափի մահճակալով և փոքր պատշգամբով, որտեղից մասամբ երևում է Կասկադի վերին տեռասները։ Այն հարմար է մեկ կամ երկու հյուրի համար, ովքեր ցանկանում են ոտքով հասնել Կասկադի աստիճաններ, Կաֆեսճյան կենտրոն և Օպերայի հրապարակ՝ ավտոմեքենայի փոխարեն։ Վերելակ չկա, ուստի բնակարանը գտնվում է երրորդ հարկում առանց վերելակի։',
      },
      ru: {
        title: 'Студия Cascade View',
        summary:
          'Компактная студия в двух кварталах от Каскада, лучше всего подходит для одного путешественника или пары.',
        description:
          'Студия Cascade View — это единое открытое пространство с мини-кухней вдоль одной стены, кроватью размера queen и небольшим балконом, откуда частично видны верхние террасы комплекса Каскад. Подходит одному-двум гостям, которые хотят дойти пешком до лестницы Каскада, центра Кафесджяна и площади Оперы, а не ехать на машине. Лифта нет — квартира находится на третьем этаже.',
      },
    },
    amenities: ['WiFi', 'Kitchen', 'Air Conditioning'],
    policies: [
      { code: 'pets_allowed', value: 'false' },
      { code: 'smoking_allowed', value: 'false' },
      { code: 'children_allowed', value: 'true' },
      { code: 'cancellation_policy', value: 'MODERATE' },
      { code: 'check_in_time', value: '15:00' },
      { code: 'check_out_time', value: '11:00' },
    ],
    units: [
      {
        type: 'PROPERTY_UNIT',
        label: 'Whole Studio',
        capacity: 1,
        maxGuests: 2,
      },
    ],
  },
  {
    partner: 'apartments',
    listingType: 'PROPERTY',
    categorySlug: 'apartments',
    citySlug: 'yerevan',
    slug: 'sprintj-opera-district-family-apartment',
    pricingModel: 'PER_NIGHT',
    amount: 26000,
    images: ['apartments-3.svg', 'apartments-4.svg'],
    translations: {
      en: {
        title: 'Opera District Family Apartment',
        summary:
          'A two-bedroom apartment near Opera Square with a full kitchen, sized for a family of four.',
        description:
          'This two-bedroom apartment sits on a residential street a few minutes’ walk from Opera Square and the Northern Avenue shops. The second bedroom has twin beds, making it a practical fit for a family with children rather than a group of friends. The kitchen is fully equipped for cooking rather than just reheating, and there’s an in-unit washing machine, useful for a longer stay.',
      },
      hy: {
        title: 'Օպերայի Թաղամասի Ընտանեկան Բնակարան',
        summary:
          'Երկու սենյականոց բնակարան Օպերայի հրապարակի մոտ՝ լիարժեք խոհանոցով, նախատեսված չորսհոգանոց ընտանիքի համար։',
        description:
          'Այս երկու սենյականոց բնակարանը գտնվում է բնակելի փողոցում՝ Օպերայի հրապարակից և Հյուսիսային պողոտայի խանութներից մի քանի րոպե քայլելու հեռավորության վրա։ Երկրորդ սենյակում կան երկու առանձին մահճակալներ, ինչը այն դարձնում է գործնական ընտրություն երեխաներով ընտանիքի, այլ ոչ թե ընկերների խմբի համար։ Խոհանոցը լիովին կահավորված է իրական ուտեստ պատրաստելու, ոչ միայն տաքացնելու համար, իսկ բնակարանում կա լվացքի մեքենա, որը օգտակար է ավելի երկար կեցության դեպքում։',
      },
      ru: {
        title: 'Семейная квартира в районе Оперы',
        summary:
          'Двухкомнатная квартира рядом с площадью Оперы с полноценной кухней, рассчитанная на семью из четырёх человек.',
        description:
          'Эта двухкомнатная квартира расположена на жилой улице в нескольких минутах ходьбы от площади Оперы и магазинов Северного проспекта. Во второй спальне — две раздельные кровати, что делает квартиру практичным вариантом для семьи с детьми, а не для компании друзей. Кухня полностью оборудована для готовки, а не только для разогрева, а стиральная машина в квартире удобна при более длительном проживании.',
      },
    },
    amenities: ['WiFi', 'Kitchen', 'Washing Machine', 'Family Friendly'],
    policies: [
      { code: 'pets_allowed', value: 'false' },
      { code: 'smoking_allowed', value: 'false' },
      { code: 'children_allowed', value: 'true' },
      { code: 'cancellation_policy', value: 'MODERATE' },
      { code: 'check_in_time', value: '15:00' },
      { code: 'check_out_time', value: '11:00' },
    ],
    units: [
      {
        type: 'PROPERTY_UNIT',
        label: 'Whole Apartment',
        capacity: 1,
        maxGuests: 4,
      },
    ],
  },
  {
    partner: 'apartments',
    listingType: 'PROPERTY',
    categorySlug: 'apartments',
    citySlug: 'gyumri',
    slug: 'sprintj-gyumri-old-town-apartment',
    pricingModel: 'PER_NIGHT',
    amount: 11000,
    images: ['apartments-5.svg', 'apartments-6.svg'],
    translations: {
      en: {
        title: 'Gyumri Old Town Apartment',
        summary:
          'A one-bedroom apartment inside a renovated courtyard building in Gyumri’s historic center.',
        description:
          'This one-bedroom apartment is on the second floor of a courtyard building typical of Gyumri’s old town, renovated inside while the street-facing stonework was left untouched. It suits a couple or a small family who want a real kitchen and living space rather than a hotel room, within walking distance of Kumayri Historic District and the city’s museums.',
      },
      hy: {
        title: 'Գյումրու Հին Քաղաքի Բնակարան',
        summary:
          'Մեկ ննջասենյականոց բնակարան Գյումրու պատմական կենտրոնի վերանորոգված բակային շենքում։',
        description:
          'Այս մեկ ննջասենյականոց բնակարանը գտնվում է Գյումրու հին քաղաքին բնորոշ բակային շենքի երկրորդ հարկում, որի ներսը վերանորոգված է, մինչդեռ փողոցին նայող քարե ճակատամասը մնացել է անփոփոխ։ Այն հարմար է զույգի կամ փոքր ընտանիքի համար, ովքեր ցանկանում են իրական խոհանոց և բնակելի տարածք ունենալ՝ հյուրանոցային սենյակի փոխարեն, Կումայրու պատմական թաղամասից և քաղաքի թանգարաններից քայլելու հեռավորության վրա։',
      },
      ru: {
        title: 'Квартира в старом городе Гюмри',
        summary:
          'Однокомнатная квартира в отреставрированном дворовом доме в историческом центре Гюмри.',
        description:
          'Эта однокомнатная квартира находится на втором этаже дворового дома, типичного для старого города Гюмри: внутри проведён ремонт, а каменный фасад, выходящий на улицу, оставлен нетронутым. Подходит паре или небольшой семье, которые хотят настоящую кухню и жилое пространство вместо гостиничного номера, в пешей доступности от исторического квартала Кумайри и городских музеев.',
      },
    },
    amenities: ['WiFi', 'Kitchen', 'Family Friendly'],
    policies: [
      { code: 'pets_allowed', value: 'true' },
      { code: 'smoking_allowed', value: 'false' },
      { code: 'children_allowed', value: 'true' },
      { code: 'cancellation_policy', value: 'FLEXIBLE' },
      { code: 'check_in_time', value: '14:00' },
      { code: 'check_out_time', value: '11:00' },
    ],
    units: [
      {
        type: 'PROPERTY_UNIT',
        label: 'Whole Apartment',
        capacity: 1,
        maxGuests: 3,
      },
    ],
  },

  // === VILLAS (Armenian Highland Retreats) ================================
  {
    partner: 'properties',
    listingType: 'PROPERTY',
    categorySlug: 'villas',
    citySlug: 'sevan',
    slug: 'sprintj-sevan-lakeside-villa',
    pricingModel: 'PER_NIGHT',
    amount: 65000,
    images: ['villas-1.svg', 'villas-2.svg'],
    translations: {
      en: {
        title: 'Sevan Lakeside Villa',
        summary:
          'A four-bedroom villa with a private lawn and terrace directly on the Lake Sevan shoreline.',
        description:
          'Sevan Lakeside Villa sits on a fenced private plot running down to the water, with an outdoor dining terrace, a barbecue area, and direct lake access rather than a shared beach. Four bedrooms sleep up to eight guests, making it a fit for two families traveling together or an extended group. The living area has a wood-burning stove for cooler evenings, since Sevan’s altitude keeps nights cool even in summer.',
      },
      hy: {
        title: 'Սևան Լեյքսայդ Վիլլա',
        summary:
          'Չորս ննջասենյականոց վիլլա՝ մասնավոր բարդով ու տեռասով անմիջապես Սևանա լճի ափին։',
        description:
          'Սևան Լեյքսայդ Վիլլան տեղակայված է ցանկապատված մասնավոր հողամասում, որն իջնում է մինչև ջուրը՝ բացօթյա ճաշասենյակի տեռասով, խորովածանոցով և ուղղակի լճի հասանելիությամբ, այլ ոչ թե ընդհանուր լողափով։ Չորս ննջասենյակները տեղավորում են մինչև ութ հյուր, ինչը այն դարձնում է հարմար երկու ընտանիքով միասին ճամփորդողների կամ մեծ խմբի համար։ Հյուրասենյակում կա փայտավառ վառարան զովացող երեկոների համար, քանի որ Սևանի բարձրադիրությունը գիշերները զովացնում է նույնիսկ ամռանը։',
      },
      ru: {
        title: 'Вилла Sevan Lakeside',
        summary:
          'Вилла с четырьмя спальнями, собственной лужайкой и террасой прямо на берегу озера Севан.',
        description:
          'Вилла Sevan Lakeside расположена на огороженном частном участке, спускающемся к воде, с террасой для трапез на открытом воздухе, зоной барбекю и прямым выходом к озеру, а не общим пляжем. Четыре спальни вмещают до восьми гостей, что делает виллу подходящей для двух семей, путешествующих вместе, или большой компании. В гостиной есть дровяная печь для прохладных вечеров — из-за высоты над уровнем моря на Севане прохладно даже летом.',
      },
    },
    amenities: [
      'WiFi',
      'Parking',
      'BBQ',
      'Terrace',
      'Fireplace',
      'Family Friendly',
    ],
    policies: [
      { code: 'pets_allowed', value: 'true' },
      { code: 'smoking_allowed', value: 'false' },
      { code: 'children_allowed', value: 'true' },
      { code: 'cancellation_policy', value: 'MODERATE' },
      { code: 'check_in_time', value: '16:00' },
      { code: 'check_out_time', value: '11:00' },
    ],
    units: [
      {
        type: 'PROPERTY_UNIT',
        label: 'Whole Villa',
        capacity: 1,
        maxGuests: 8,
      },
    ],
  },
  {
    partner: 'properties',
    listingType: 'PROPERTY',
    categorySlug: 'villas',
    citySlug: 'dilijan',
    slug: 'sprintj-dilijan-forest-villa',
    pricingModel: 'PER_NIGHT',
    amount: 48000,
    images: ['villas-3.svg', 'villas-4.svg'],
    translations: {
      en: {
        title: 'Dilijan Forest Villa',
        summary:
          'A three-bedroom villa set into a forested hillside on the edge of Dilijan National Park.',
        description:
          'Dilijan Forest Villa is built up a wooded slope a short drive from Dilijan’s old town, surrounded by the beech forest the national park is known for rather than open lawn. Large windows face the tree line, and a covered deck stays usable even in light rain. Three bedrooms suit a group of up to six who came for hiking trails rather than a lakeside beach scene.',
      },
      hy: {
        title: 'Դիլիջան Ֆորեստ Վիլլա',
        summary:
          'Երեք ննջասենյականոց վիլլա՝ անտառապատ լանջի վրա, Դիլիջանի ազգային պարկի եզրին։',
        description:
          'Դիլիջան Ֆորեստ Վիլլան կառուցված է անտառապատ լանջի վրա՝ Դիլիջանի հին քաղաքից կարճ մեքենայով հեռավորության վրա, շրջապատված հաճարենու անտառով, որով հայտնի է ազգային պարկը, այլ ոչ թե բաց բարդով։ Մեծ պատուհանները նայում են ծառերի շարքին, իսկ ծածկված պատշգամբը մնում է օգտագործելի նույնիսկ թեթև անձրևի ժամանակ։ Երեք ննջասենյակները հարմար են մինչև վեց հոգանոց խմբի համար, ովքեր եկել են արշավային արահետների, ոչ թե լճափնյա հանգստի համար։',
      },
      ru: {
        title: 'Вилла Dilijan Forest',
        summary:
          'Вилла с тремя спальнями на лесистом склоне на краю Дилижанского национального парка.',
        description:
          'Вилла Dilijan Forest построена на лесистом склоне в нескольких минутах езды от старого города Дилижан, окружённая буковым лесом, которым славится национальный парк, а не открытой лужайкой. Большие окна выходят на линию деревьев, а крытая терраса остаётся пригодной для использования даже при небольшом дожде. Три спальни подходят для компании до шести человек, приехавших ради пеших маршрутов, а не пляжного отдыха у озера.',
      },
    },
    amenities: [
      'WiFi',
      'Parking',
      'Fireplace',
      'Terrace',
      'Kitchen',
      'Pet Friendly',
    ],
    policies: [
      { code: 'pets_allowed', value: 'true' },
      { code: 'smoking_allowed', value: 'false' },
      { code: 'children_allowed', value: 'true' },
      { code: 'cancellation_policy', value: 'MODERATE' },
      { code: 'check_in_time', value: '15:00' },
      { code: 'check_out_time', value: '11:00' },
    ],
    units: [
      {
        type: 'PROPERTY_UNIT',
        label: 'Whole Villa',
        capacity: 1,
        maxGuests: 6,
      },
    ],
  },
  {
    partner: 'properties',
    listingType: 'PROPERTY',
    categorySlug: 'villas',
    citySlug: 'jermuk',
    slug: 'sprintj-jermuk-hot-spring-villa',
    pricingModel: 'PER_NIGHT',
    amount: 55000,
    images: ['villas-5.svg', 'villas-6.svg'],
    translations: {
      en: {
        title: 'Jermuk Hot Spring Villa',
        summary:
          'A two-bedroom villa in Jermuk with its own spring-fed outdoor tub, built for a couple or a small group.',
        description:
          'This villa channels the same mineral-spring water Jermuk is known for into a small outdoor tub on its own deck, set apart from the town’s larger public spa facilities. Two bedrooms keep it intimate rather than a big group rental, and the kitchen is stocked for self-catering during a quiet weekend away. The gorge trail toward Jermuk’s waterfall starts a few minutes down the road.',
      },
      hy: {
        title: 'Ջերմուկ Հոթ Սփրինգ Վիլլա',
        summary:
          'Երկու ննջասենյականոց վիլլա Ջերմուկում՝ սեփական աղբյուրային բացօթյա լոգարանով, նախատեսված զույգի կամ փոքր խմբի համար։',
        description:
          'Այս վիլլան օգտագործում է Ջերմուկին բնորոշ նույն հանքային ջուրը՝ մղելով այն սեփական տախտակամածի վրայի փոքրիկ բացօթյա լոգարան, առանձնացված քաղաքի ավելի մեծ հանրային սպա հաստատություններից։ Երկու ննջասենյակները այն դարձնում են ավելի ինտիմ, քան մեծ խմբի համար վարձակալություն, իսկ խոհանոցը հագեցած է ինքնուրույն ուտեստ պատրաստելու համար՝ հանգիստ հանգստյան օրերին։ Ջերմուկի ջրվեժ տանող կիրճի արահետը սկսվում է ճանապարհից մի քանի րոպե հեռավորության վրա։',
      },
      ru: {
        title: 'Вилла Jermuk Hot Spring',
        summary:
          'Вилла с двумя спальнями в Джермуке с собственной купелью на минеральной воде, рассчитанная на пару или небольшую компанию.',
        description:
          'Эта вилла подаёт ту же минеральную воду, которой славится Джермук, в небольшую купель на собственной террасе, отдельно от крупных общественных спа-комплексов города. Две спальни делают её более камерной, чем аренда для большой группы, а кухня укомплектована для самостоятельного приготовления еды во время тихих выходных. Тропа к ущелью и водопаду Джермук начинается в нескольких минутах по дороге.',
      },
    },
    amenities: ['WiFi', 'Parking', 'Kitchen', 'Air Conditioning'],
    policies: [
      { code: 'pets_allowed', value: 'false' },
      { code: 'smoking_allowed', value: 'false' },
      { code: 'children_allowed', value: 'true' },
      { code: 'cancellation_policy', value: 'STRICT' },
      { code: 'check_in_time', value: '16:00' },
      { code: 'check_out_time', value: '12:00' },
    ],
    units: [
      {
        type: 'PROPERTY_UNIT',
        label: 'Whole Villa',
        capacity: 1,
        maxGuests: 4,
      },
    ],
  },

  // === GUEST HOUSES (Armenian Highland Retreats) ==========================
  {
    partner: 'properties',
    listingType: 'PROPERTY',
    categorySlug: 'guest-houses',
    citySlug: 'gyumri',
    slug: 'sprintj-gyumri-heritage-guesthouse',
    pricingModel: 'PER_NIGHT',
    amount: 12000,
    images: ['guest-houses-1.svg', 'guest-houses-2.svg'],
    translations: {
      en: {
        title: 'Gyumri Heritage Guesthouse',
        summary:
          'A family-run guesthouse in a restored 19th-century home, with breakfast included every morning.',
        description:
          'The same family has run this guesthouse out of their own restored home for years, renting out three of its rooms while living in the rest. Breakfast is served at a shared table in the kitchen rather than a separate dining room, usually with the host explaining the neighborhood’s history over coffee. It suits a traveler who wants a genuine local connection more than hotel-style privacy.',
      },
      hy: {
        title: 'Գյումրի Հերիտաժ Հյուրատուն',
        summary:
          'Ընտանեկան հյուրատուն XIX դարի վերականգնված տանը՝ նախաճաշը ներառված է ամեն առավոտ։',
        description:
          'Նույն ընտանիքն արդեն տարիներ շարունակ վարում է այս հյուրատունը իրենց սեփական վերականգնված տնից՝ վարձով տալով երեք սենյակ, մինչդեռ ինքն ապրում է մնացած մասում։ Նախաճաշը մատուցվում է խոհանոցի ընդհանուր սեղանին, ոչ թե առանձին ճաշասենյակում, և հաճախ հյուրընկալողը սուրճի ընթացքում պատմում է թաղամասի պատմության մասին։ Այն հարմար է ճամփորդի համար, ով ցանկանում է իրական տեղական կապ ունենալ, քան հյուրանոցային անձնական տարածք։',
      },
      ru: {
        title: 'Гостевой дом Gyumri Heritage',
        summary:
          'Семейный гостевой дом в восстановленном доме XIX века, завтрак включён каждое утро.',
        description:
          'Одна и та же семья годами содержит этот гостевой дом в собственном отреставрированном доме, сдавая три комнаты, а сама живёт в остальной части. Завтрак подаётся за общим столом на кухне, а не в отдельной столовой, и хозяева часто рассказывают за кофе об истории района. Подходит путешественнику, который ценит настоящую местную связь больше, чем гостиничную приватность.',
      },
    },
    amenities: ['WiFi', 'Parking', 'Breakfast Included', 'Family Friendly'],
    policies: [
      { code: 'pets_allowed', value: 'false' },
      { code: 'smoking_allowed', value: 'false' },
      { code: 'children_allowed', value: 'true' },
      { code: 'cancellation_policy', value: 'FLEXIBLE' },
      { code: 'check_in_time', value: '14:00' },
      { code: 'check_out_time', value: '11:00' },
    ],
    units: [
      { type: 'PROPERTY_UNIT', label: 'Guest Room', capacity: 3, maxGuests: 2 },
    ],
  },
  {
    partner: 'properties',
    listingType: 'PROPERTY',
    categorySlug: 'guest-houses',
    citySlug: 'goris',
    slug: 'sprintj-goris-cave-country-guesthouse',
    pricingModel: 'PER_NIGHT',
    amount: 10000,
    images: ['guest-houses-3.svg', 'guest-houses-4.svg'],
    translations: {
      en: {
        title: 'Goris Cave-Country Guesthouse',
        summary:
          'A simple mountain guesthouse in Goris, a short drive from the Khndzoresk cave village.',
        description:
          'This guesthouse is a practical base for exploring the rock formations around Goris and the abandoned cave village at Khndzoresk, rather than a destination on its own. Rooms are plain and warm, with thick blankets for cold mountain nights. The hosts pack a simple lunch on request for guests heading out early to beat the day-trip crowds.',
      },
      hy: {
        title: 'Գորիս Քեյվ-Քանթրի Հյուրատուն',
        summary:
          'Պարզ լեռնային հյուրատուն Գորիսում՝ Խնձորեսկի քարանձավային գյուղից կարճ մեքենայով հեռավորության վրա։',
        description:
          'Այս հյուրատունը գործնական բազա է Գորիսի շրջակա ժայռային կազմավորումները և Խնձորեսկի լքված քարանձավային գյուղը ուսումնասիրելու համար, այլ ոչ թե ինքնուրույն ուղղություն։ Սենյակները պարզ են ու ջերմ, հաստ վերմակներով՝ սառը լեռնային գիշերների համար։ Հյուրընկալողները պահանջով պատրաստում են պարզ ճաշ այն հյուրերի համար, ովքեր վաղ են մեկնում՝ օրվա էքսկուրսիաների ամբոխից առաջ ընկնելու համար։',
      },
      ru: {
        title: 'Гостевой дом Goris Cave-Country',
        summary:
          'Простой горный гостевой дом в Горисе, в нескольких минутах езды от пещерного села Хндзореск.',
        description:
          'Этот гостевой дом служит практичной базой для изучения скальных образований вокруг Гориса и заброшенного пещерного села Хндзореск, а не самостоятельной целью поездки. Номера простые и тёплые, с плотными одеялами для холодных горных ночей. По запросу хозяева собирают простой обед для гостей, выезжающих рано утром, чтобы опередить дневные группы туристов.',
      },
    },
    amenities: ['WiFi', 'Parking', 'Garden', 'Family Friendly'],
    policies: [
      { code: 'pets_allowed', value: 'true' },
      { code: 'smoking_allowed', value: 'false' },
      { code: 'children_allowed', value: 'true' },
      { code: 'cancellation_policy', value: 'MODERATE' },
      { code: 'check_in_time', value: '13:00' },
      { code: 'check_out_time', value: '10:00' },
    ],
    units: [
      { type: 'PROPERTY_UNIT', label: 'Guest Room', capacity: 4, maxGuests: 2 },
    ],
  },
  {
    partner: 'properties',
    listingType: 'PROPERTY',
    categorySlug: 'guest-houses',
    citySlug: 'ejmiatsin',
    slug: 'sprintj-ejmiatsin-pilgrims-guesthouse',
    pricingModel: 'PER_NIGHT',
    amount: 9000,
    images: ['guest-houses-5.svg', 'guest-houses-6.svg'],
    translations: {
      en: {
        title: 'Ejmiatsin Pilgrim’s Guesthouse',
        summary:
          'A quiet, budget guesthouse a few minutes’ walk from Ejmiatsin Cathedral.',
        description:
          'This guesthouse keeps things deliberately simple: clean rooms, a shared kitchen guests can use freely, and quiet after 10pm, aimed at pilgrims and travelers visiting Ejmiatsin Cathedral and the nearby Zvartnots ruins rather than anyone looking for nightlife. It’s within easy walking distance of the cathedral grounds, and the hosts can point guests toward the smaller churches scattered around town.',
      },
      hy: {
        title: 'Էջմիածին Ուխտավորի Հյուրատուն',
        summary:
          'Հանգիստ, մատչելի հյուրատուն Էջմիածնի Մայր Տաճարից մի քանի րոպե քայլելու հեռավորության վրա։',
        description:
          'Այս հյուրատունը միտումնավոր պահպանում է պարզություն՝ մաքուր սենյակներ, ընդհանուր խոհանոց, որը հյուրերն ազատորեն կարող են օգտագործել, և լռություն 22:00-ից հետո՝ ուղղված ուխտավորներին և ճամփորդներին, ովքեր այցելում են Էջմիածնի Մայր Տաճարը և մոտակա Զվարթնոցի ավերակները, ոչ թե գիշերային կյանք փնտրողներին։ Այն գտնվում է տաճարի տարածքից քայլելու հեռավորության վրա, և հյուրընկալողները կարող են ուղղորդել հյուրերին դեպի քաղաքով ցրված փոքր եկեղեցիները։',
      },
      ru: {
        title: 'Гостевой дом Ejmiatsin Pilgrim’s',
        summary:
          'Тихий недорогой гостевой дом в нескольких минутах ходьбы от Эчмиадзинского кафедрального собора.',
        description:
          'Этот гостевой дом намеренно устроен просто: чистые номера, общая кухня, которой гости могут свободно пользоваться, и тишина после 22:00 — рассчитан на паломников и путешественников, посещающих Эчмиадзинский собор и близлежащие руины Звартноца, а не на любителей ночной жизни. Он находится в пешей доступности от территории собора, а хозяева могут подсказать, где найти небольшие церкви, разбросанные по городу.',
      },
    },
    amenities: ['WiFi', 'Kitchen', 'Family Friendly'],
    policies: [
      { code: 'pets_allowed', value: 'false' },
      { code: 'smoking_allowed', value: 'false' },
      { code: 'children_allowed', value: 'true' },
      { code: 'cancellation_policy', value: 'FLEXIBLE' },
      { code: 'check_in_time', value: '13:00' },
      { code: 'check_out_time', value: '11:00' },
    ],
    units: [
      { type: 'PROPERTY_UNIT', label: 'Guest Room', capacity: 3, maxGuests: 2 },
    ],
  },

  // === RESTAURANTS (Yerevan Taste Collective) =============================
  {
    partner: 'restaurants',
    listingType: 'RESTAURANT',
    categorySlug: 'restaurants',
    citySlug: 'yerevan',
    slug: 'sprintj-toros-armenian-kitchen',
    pricingModel: 'PER_PERSON',
    amount: 6500,
    images: ['restaurants-1.svg', 'restaurants-2.svg'],
    translations: {
      en: {
        title: 'Toros Armenian Kitchen',
        summary:
          'A family-style Armenian restaurant near Republic Square serving khorovats, dolma, and fresh lavash.',
        description:
          'Toros Armenian Kitchen keeps its menu close to home cooking: khorovats grilled to order, dolma wrapped by hand, and lavash baked in a tonir visible from the dining room. Portions are meant for sharing across the table rather than individual plating, in keeping with how the dishes are eaten at home. It gets busy on weekend evenings, so a same-day reservation is worth making.',
      },
      hy: {
        title: 'Թորոս Հայկական Խոհանոց',
        summary:
          'Ընտանեկան ոճի հայկական ռեստորան՝ Հանրապետության հրապարակի մոտ, որտեղ մատուցվում է խորոված, դոլմա և թարմ լավաշ։',
        description:
          'Թորոս Հայկական Խոհանոցը իր ճաշացանկը մոտեցնում է տնային ուտեստներին՝ պատվերով խորոված, ձեռքով փաթաթված դոլմա և ճաշասենյակից տեսանելի թոնրում թխված լավաշ։ Չափաբաժինները նախատեսված են սեղանի շուրջ բաժանելու, ոչ թե անհատական մատուցման համար՝ ինչպես տանը են ուտում այս ուտեստները։ Շաբաթ-կիրակի երեկոները ռեստորանը զբաղված է, ուստի արժե նույն օրվա ամրագրում կատարել։',
      },
      ru: {
        title: 'Ресторан Toros Armenian Kitchen',
        summary:
          'Армянский ресторан домашней кухни у площади Республики: хоровац, толма и свежий лаваш.',
        description:
          'Меню Toros Armenian Kitchen близко к домашней кухне: хоровац готовится на заказ, толма заворачивается вручную, а лаваш выпекается в тонире, видном из зала. Порции рассчитаны на то, чтобы делиться ими за столом, а не подаются индивидуально — так, как эти блюда едят дома. По вечерам выходных здесь людно, поэтому стоит забронировать столик заранее в тот же день.',
      },
    },
    amenities: ['WiFi', 'Parking', 'Family Friendly'],
    policies: [
      { code: 'smoking_allowed', value: 'false' },
      { code: 'children_allowed', value: 'true' },
    ],
    units: [
      {
        type: 'RESTAURANT_TABLE',
        label: 'Main Dining Room',
        capacity: 40,
      },
    ],
  },
  {
    partner: 'restaurants',
    listingType: 'RESTAURANT',
    categorySlug: 'restaurants',
    citySlug: 'vanadzor',
    slug: 'sprintj-vanadzor-grill-house',
    pricingModel: 'PER_PERSON',
    amount: 5000,
    images: ['restaurants-3.svg', 'restaurants-4.svg'],
    translations: {
      en: {
        title: 'Vanadzor Grill House',
        summary:
          'A casual, no-frills grill house in Vanadzor built around khorovats and hearty portions.',
        description:
          'Vanadzor Grill House is a plain, functional space with plastic tablecloths and an open charcoal grill in view of the dining area — the point is the food, not the decor. Pork and chicken khorovats come with grilled vegetables and a stack of fresh lavash, sized for someone who worked up an appetite exploring Lori province. It’s a stop drivers heading toward the Debed Canyon monasteries know well.',
      },
      hy: {
        title: 'Վանաձոր Գրիլ Հաուս',
        summary:
          'Ոչ պաշտոնական, պարզ գրիլ-ռեստորան Վանաձորում՝ հիմնված խորոված և առատ չափաբաժինների վրա։',
        description:
          'Վանաձոր Գրիլ Հաուսը պարզ, ֆունկցիոնալ տարածք է՝ պլաստիկ սփռոցներով և ճաշասենյակից տեսանելի բաց ածխի գրիլով. կարևորը ուտեստն է, ոչ թե ինտերիերը։ Խոզի և հավի խորովածը մատուցվում է խորոված բանջարեղենով և թարմ լավաշի կույտով՝ նախատեսված Լոռու մարզը ուսումնասիրելիս ախորժակ ձեռք բերած մարդու համար։ Սա այն կանգառն է, որին լավ ծանոթ են Դեբեդի կիրճի վանքեր ուղևորվող վարորդները։',
      },
      ru: {
        title: 'Гриль-дом Vanadzor Grill House',
        summary:
          'Простой гриль-ресторан в Ванадзоре без излишеств, построенный вокруг хороваца и сытных порций.',
        description:
          'Vanadzor Grill House — простое функциональное место с клеёнчатыми скатертями и открытым угольным грилем на виду у зала: главное здесь — еда, а не интерьер. Свиной и куриный хоровац подаются с овощами гриль и стопкой свежего лаваша, порции рассчитаны на того, кто нагулял аппетит, исследуя провинцию Лори. Это остановка, хорошо знакомая водителям, направляющимся к монастырям Дебедского каньона.',
      },
    },
    amenities: ['Parking', 'Outdoor Seating', 'Family Friendly'],
    policies: [
      { code: 'smoking_allowed', value: 'true' },
      { code: 'children_allowed', value: 'true' },
    ],
    units: [
      {
        type: 'RESTAURANT_TABLE',
        label: 'Dining Hall',
        capacity: 30,
      },
    ],
  },
  {
    partner: 'restaurants',
    listingType: 'RESTAURANT',
    categorySlug: 'restaurants',
    citySlug: 'sevan',
    slug: 'sprintj-sevan-lake-fish-terrace',
    pricingModel: 'PER_PERSON',
    amount: 9000,
    images: ['restaurants-5.svg', 'restaurants-6.svg'],
    translations: {
      en: {
        title: 'Sevan Lake Fish Terrace',
        summary:
          'A lakeside terrace restaurant specializing in Sevan trout (ishkhan) and other freshwater fish.',
        description:
          'Sevan Lake Fish Terrace sits directly on the shoreline with an open-air terrace that seats most tables outdoors in season. The menu centers on ishkhan (Sevan trout) grilled whole or pan-fried, alongside crayfish when they’re in season, priced higher than an inland restaurant because of the fish itself rather than any added formality. Tables closest to the water fill up first, so arriving before sunset is worth it.',
      },
      hy: {
        title: 'Սևան Լեյք Ֆիշ Թերասե',
        summary:
          'Լճափնյա տեռասով ռեստորան, որը մասնագիտացած է սևանյան իշխանով և այլ քաղցրահամ ջրերի ձկներով։',
        description:
          'Սևան Լեյք Ֆիշ Թերասեն տեղակայված է անմիջապես ափին՝ բացօթյա տեռասով, որտեղ սեզոնին սեղանների մեծ մասը դրված է դրսում։ Ճաշացանկի կենտրոնում ամբողջական խորոված կամ տապակած իշխանն է, իսկ սեզոնին՝ նաև խեցգետիններ, գինը ավելի բարձր է, քան ցամաքային ռեստորանում, հենց ձկան պատճառով, ոչ թե ավելորդ ֆորմալության։ Ջրին ամենամոտ սեղանները առաջինն են լցվում, ուստի արժե գալ մայրամուտից առաջ։',
      },
      ru: {
        title: 'Терраса Sevan Lake Fish',
        summary:
          'Ресторан-терраса на берегу озера, специализирующийся на севанской форели (ишхан) и другой пресноводной рыбе.',
        description:
          'Sevan Lake Fish Terrace расположен прямо на берегу, с открытой террасой, где в сезон стоит большинство столиков. В центре меню — ишхан (севанская форель), приготовленный целиком на гриле или обжаренный, а в сезон также раки; цены выше, чем в ресторане вдали от озера, именно из-за самой рыбы, а не показной формальности. Столики ближе к воде заполняются первыми, поэтому стоит прийти до заката.',
      },
    },
    amenities: ['Parking', 'Outdoor Seating', 'WiFi'],
    policies: [
      { code: 'smoking_allowed', value: 'false' },
      { code: 'children_allowed', value: 'true' },
    ],
    units: [
      {
        type: 'RESTAURANT_TABLE',
        label: 'Lakeside Terrace',
        capacity: 24,
      },
    ],
  },

  // === TOURS (Trans-Caucasus Journeys) =====================================
  {
    partner: 'tours',
    listingType: 'TOUR',
    categorySlug: 'tours',
    citySlug: 'yerevan',
    slug: 'sprintj-areni-wine-cave-day-trip',
    pricingModel: 'PER_PERSON',
    amount: 15000,
    images: ['tours-1.svg', 'tours-2.svg'],
    translations: {
      en: {
        title: 'Areni Wine & Cave Day Trip',
        summary:
          'A full-day trip from Yerevan combining the Areni-1 cave complex, Noravank monastery, and a village winery tasting.',
        description:
          'This day trip departs Yerevan by minivan and heads to the Areni-1 cave, where archaeologists found the world’s oldest known winery remains, before continuing to Noravank monastery for its cliffside setting. The day ends at a small family winery in Areni village for a guided tasting of local Areni-grape wine. Lunch is included at a village guesthouse along the route.',
      },
      hy: {
        title: 'Արենի Գինու և Քարանձավի Մեկօրյա Ճամփորդություն',
        summary:
          'Մեկօրյա ուղևորություն Երևանից՝ համատեղելով Արենի-1 քարանձավային համալիրը, Նորավանք վանքը և գյուղական գինու համտեսը։',
        description:
          'Այս մեկօրյա ուղևորությունը մեկնում է Երևանից միկրոավտոբուսով և ուղղվում դեպի Արենի-1 քարանձավ, որտեղ հնագետները գտել են աշխարհի ամենահին հայտնի գինեգործարանի մնացորդները, այնուհետև շարունակվում դեպի Նորավանք վանք՝ իր ժայռափոր տեղադրությամբ։ Օրը ավարտվում է Արենի գյուղի փոքրիկ ընտանեկան գինեգործարանում՝ տեղական Արենի սորտի գինու ուղեկցվող համտեսով։ Ճանապարհի ընթացքում ներառված է ճաշ գյուղական հյուրատանը։',
      },
      ru: {
        title: 'Однодневная поездка Арени — вино и пещера',
        summary:
          'Поездка из Еревана на целый день, объединяющая пещерный комплекс Арени-1, монастырь Нораванк и дегустацию в деревенской винодельне.',
        description:
          'Эта однодневная поездка отправляется из Еревана на минивэне к пещере Арени-1, где археологи обнаружили древнейшие в мире следы винодельни, а затем продолжается к монастырю Нораванк с его скальным расположением. День завершается в небольшой семейной винодельне в селе Арени дегустацией местного вина из сорта Арени под руководством гида. По пути включён обед в деревенском гостевом доме.',
      },
    },
    amenities: ['Family Friendly'],
    policies: [
      { code: 'cancellation_policy', value: 'MODERATE' },
      { code: 'children_allowed', value: 'true' },
    ],
    units: [
      {
        type: 'TOUR_DEPARTURE',
        label: 'Shared Group Departure',
        capacity: 12,
      },
    ],
  },
  {
    partner: 'tours',
    listingType: 'TOUR',
    categorySlug: 'tours',
    citySlug: 'sevan',
    slug: 'sprintj-lake-sevan-monastery-hike',
    pricingModel: 'PER_PERSON',
    amount: 9000,
    images: ['tours-3.svg', 'tours-4.svg'],
    translations: {
      en: {
        title: 'Lake Sevan Monastery Hike',
        summary:
          'A half-day guided hike to Sevanavank monastery and along the lake’s northern shore trail.',
        description:
          'This trip starts with the short but steep climb to Sevanavank monastery on its peninsula overlooking the lake, then continues onto a flatter shoreline trail rarely used by day-trip buses. The guide points out the difference between the old and new shorelines left by the lake’s Soviet-era water level changes. Sturdy shoes are recommended; sandals are not a good fit for the monastery steps.',
      },
      hy: {
        title: 'Սևանա Լճի Վանքի Արշավ',
        summary:
          'Կիսօրյա ուղեկցվող արշավ դեպի Սևանավանք և լճի հյուսիսային ափի արահետով։',
        description:
          'Այս ճամփորդությունը սկսվում է կարճ, բայց զառիթափ բարձրացումով դեպի Սևանավանք՝ լիճը նայող թերակղզու վրա, այնուհետև շարունակվում է ավելի հարթ ափամերձ արահետով, որը հազվադեպ է օգտագործվում մեկօրյա էքսկուրսիաների ավտոբուսներով։ Ուղեկցորդը ցույց է տալիս հին և նոր ափագծերի տարբերությունը, որոնք մնացել են լճի խորհրդային ժամանակաշրջանի ջրի մակարդակի փոփոխություններից։ Խորհուրդ է տրվում ամուր կոշիկ. սանդալները հարմար չեն վանքի աստիճանների համար։',
      },
      ru: {
        title: 'Поход к монастырю у озера Севан',
        summary:
          'Полудневный поход с гидом к монастырю Севанаванк и вдоль тропы по северному берегу озера.',
        description:
          'Поездка начинается с короткого, но крутого подъёма к монастырю Севанаванк на полуострове с видом на озеро, затем продолжается по более пологой прибрежной тропе, редко используемой автобусами однодневных туров. Гид рассказывает о разнице между старой и новой береговой линией, оставшейся после изменений уровня воды в советское время. Рекомендуется удобная обувь — сандалии не подходят для ступеней монастыря.',
      },
    },
    amenities: ['Wheelchair Accessible', 'Family Friendly'],
    policies: [
      { code: 'cancellation_policy', value: 'FLEXIBLE' },
      { code: 'children_allowed', value: 'true' },
    ],
    units: [
      { type: 'TOUR_DEPARTURE', label: 'Shared Group Departure', capacity: 10 },
    ],
  },
  {
    partner: 'tours',
    listingType: 'TOUR',
    categorySlug: 'tours',
    citySlug: 'vanadzor',
    slug: 'sprintj-debed-canyon-monastery-tour',
    pricingModel: 'PER_PERSON',
    amount: 13000,
    images: ['tours-5.svg', 'tours-6.svg'],
    translations: {
      en: {
        title: 'Debed Canyon Monastery Tour',
        summary:
          'A full-day trip from Vanadzor to the UNESCO-listed Haghpat and Sanahin monasteries in the Debed Canyon.',
        description:
          'This trip departs Vanadzor and follows the Debed River gorge to Haghpat monastery, then across the canyon to its sister complex at Sanahin — both UNESCO World Heritage sites from the same 10th-century monastic tradition. The guide explains the architectural details that distinguish the two, which look similar at a glance but were built decades apart. A stop at a roadside stand for local fruit preserves rounds out the trip.',
      },
      hy: {
        title: 'Դեբեդի Կիրճի Վանքերի Տուր',
        summary:
          'Մեկօրյա ուղևորություն Վանաձորից դեպի ՅՈՒՆԵՍԿՕ-ի ցանկում գտնվող Հաղպատ և Սանահին վանքերը Դեբեդի կիրճում։',
        description:
          'Այս ուղևորությունը մեկնում է Վանաձորից և հետևում է Դեբեդ գետի կիրճին մինչև Հաղպատ վանք, այնուհետև կիրճով անցնում է դեպի նրա քույր համալիրը՝ Սանահին, երկուսն էլ ՅՈՒՆԵՍԿՕ-ի համաշխարհային ժառանգության հուշարձաններ են՝ նույն X դարի վանական ավանդույթից։ Ուղեկցորդը բացատրում է ճարտարապետական մանրամասները, որոնք տարբերում են այս երկուսը, որոնք առաջին հայացքից նման են, բայց կառուցվել են տասնամյակների տարբերությամբ։ Ճանապարհին կանգառ է կատարվում տեղական մրգային մուրաբա վաճառող կրպակի մոտ։',
      },
      ru: {
        title: 'Тур по монастырям Дебедского каньона',
        summary:
          'Однодневная поездка из Ванадзора к монастырям Ахпат и Санаин, включённым в список ЮНЕСКО, в Дебедском каньоне.',
        description:
          'Поездка отправляется из Ванадзора и следует вдоль ущелья реки Дебед к монастырю Ахпат, затем через каньон к его «парному» комплексу в Санаине — оба объекта всемирного наследия ЮНЕСКО относятся к одной монашеской традиции X века. Гид объясняет архитектурные детали, которые отличают эти два комплекса, на первый взгляд похожие, но построенные с разницей в десятилетия. Поездку дополняет остановка у придорожного прилавка с местным вареньем.',
      },
    },
    amenities: ['Family Friendly'],
    policies: [
      { code: 'cancellation_policy', value: 'MODERATE' },
      { code: 'children_allowed', value: 'true' },
    ],
    units: [
      { type: 'TOUR_DEPARTURE', label: 'Shared Group Departure', capacity: 14 },
    ],
  },

  // === CAR RENTALS (Ararat Motor Rentals) ==================================
  {
    partner: 'carRentals',
    listingType: 'CAR_RENTAL',
    categorySlug: 'car-rentals',
    citySlug: 'yerevan',
    slug: 'sprintj-economy-city-car-compact-class',
    pricingModel: 'PER_DAY',
    amount: 12000,
    images: ['car-rentals-1.svg', 'car-rentals-2.svg'],
    translations: {
      en: {
        title: 'Economy City Car — Compact Class',
        summary:
          'A manual-transmission compact car, well suited to Yerevan city driving and parking.',
        description:
          'This compact class covers small manual-transmission hatchbacks, easy to park on Yerevan’s narrower side streets and cheap enough on fuel for daily city driving. It’s not built for long mountain drives with a full trunk of luggage — for that, the SUV in this same fleet is the better fit. Pickup and return are both at the Yerevan city office.',
      },
      hy: {
        title: 'Էկոնոմ Քաղաքային Մեքենա — Կոմպակտ Դաս',
        summary:
          'Մեխանիկական փոխանցումատուփով կոմպակտ մեքենա, հարմար Երևանում վարելու և կայանելու համար։',
        description:
          'Այս կոմպակտ դասը ներառում է փոքր մեխանիկական հեչբեքներ, որոնք հեշտ է կայանել Երևանի ավելի նեղ կողքի փողոցներում և բավականաչափ խնայողական են վառելիքի առումով ամենօրյա քաղաքային վարման համար։ Այն նախատեսված չէ ամբողջովին բեռնված բեռնախցիկով երկար լեռնային երթուղիների համար. դրա համար ավելի հարմար է նույն ավտոպարկի ամենագնացը։ Ստացումն ու վերադարձը կատարվում են Երևանի քաղաքային գրասենյակում։',
      },
      ru: {
        title: 'Эконом-класс — компактный автомобиль',
        summary:
          'Компактный автомобиль с механической коробкой передач, удобен для езды и парковки в Ереване.',
        description:
          'Этот компактный класс включает небольшие хетчбэки с механической коробкой передач — их легко парковать на более узких улицах Еревана, и они экономичны для ежедневной езды по городу. Он не рассчитан на дальние горные поездки с полным багажником — для этого в этом же парке есть внедорожник. Получение и возврат автомобиля — в городском офисе в Ереване.',
      },
    },
    amenities: ['Air Conditioning'],
    policies: [
      { code: 'smoking_allowed', value: 'false' },
      { code: 'cancellation_policy', value: 'MODERATE' },
    ],
    units: [{ type: 'VEHICLE', label: 'Compact Hatchback', capacity: 3 }],
  },
  {
    partner: 'carRentals',
    listingType: 'CAR_RENTAL',
    categorySlug: 'car-rentals',
    citySlug: 'yerevan',
    slug: 'sprintj-highland-suv-4x4-mountain-explorer',
    pricingModel: 'PER_DAY',
    amount: 28000,
    images: ['car-rentals-3.svg', 'car-rentals-4.svg'],
    translations: {
      en: {
        title: 'Highland SUV — 4x4 Mountain Explorer',
        summary:
          'A 4x4 SUV with real ground clearance, built for the unpaved roads to Tatev, Khndzoresk, and mountain villages.',
        description:
          'This SUV class is what this fleet recommends for anywhere off Armenia’s main paved highways: the unpaved stretches toward Tatev, the mountain roads above Dilijan, or village routes that a compact car would struggle with. It seats up to five with real luggage space in the back. Four-wheel drive is genuine, not a badge — worth confirming with the fleet’s reservations desk if a specific route is planned.',
      },
      hy: {
        title: 'Հայլենդ Ամենագնաց — 4x4 Լեռնային Էքսպլորեր',
        summary:
          'Իրական ճանապարհային բացվածքով 4x4 ամենագնաց, նախատեսված Տաթևի, Խնձորեսկի և լեռնային գյուղերի չասֆալտապատ ճանապարհների համար։',
        description:
          'Այս ամենագնաց դասը այն է, ինչ ավտոպարկը խորհուրդ է տալիս Հայաստանի հիմնական ասֆալտապատ մայրուղիներից դուրս ցանկացած ուղղության համար՝ Տաթև տանող չասֆալտապատ հատվածները, Դիլիջանից վերև գտնվող լեռնային ճանապարհները կամ գյուղական երթուղիները, որոնց հետ կոմպակտ մեքենան դժվարությամբ կհամապատասխանի։ Այն տեղավորում է մինչև հինգ հոգի՝ իրական ուղեբեռի տարածքով հետևում։ Քառանիվ շարժիչը իրական է, ոչ թե պարզապես անվանում. արժե հաստատել ավտոպարկի ամրագրումների սեղանի հետ, եթե պլանավորված է կոնկրետ երթուղի։',
      },
      ru: {
        title: 'Внедорожник Highland — 4x4 Mountain Explorer',
        summary:
          'Полноприводный внедорожник с реальным дорожным просветом, рассчитанный на грунтовые дороги к Татеву, Хндзореску и горным сёлам.',
        description:
          'Этот класс внедорожников компания рекомендует для любых маршрутов за пределами основных асфальтированных трасс Армении: грунтовых участков по пути к Татеву, горных дорог над Дилижаном или сельских маршрутов, с которыми компактный автомобиль справится с трудом. Вмещает до пяти человек с реальным местом для багажа сзади. Полный привод настоящий, а не просто значок — стоит уточнить у стойки бронирования, если запланирован конкретный маршрут.',
      },
    },
    amenities: ['Air Conditioning', 'EV Charger'],
    policies: [
      { code: 'smoking_allowed', value: 'false' },
      { code: 'cancellation_policy', value: 'FLEXIBLE' },
    ],
    units: [{ type: 'VEHICLE', label: '4x4 SUV', capacity: 2 }],
  },
  {
    partner: 'carRentals',
    listingType: 'CAR_RENTAL',
    categorySlug: 'car-rentals',
    citySlug: 'yerevan',
    slug: 'sprintj-family-minivan-7-seater',
    pricingModel: 'PER_DAY',
    amount: 24000,
    images: ['car-rentals-5.svg', 'car-rentals-6.svg'],
    translations: {
      en: {
        title: 'Family Minivan — 7-Seater',
        summary:
          'A 7-seat minivan with automatic transmission, built for a family or small group traveling together.',
        description:
          'This minivan seats seven with three real rows rather than a cramped third-row bench, and the automatic transmission makes it an easier drive for anyone not confident with a manual on mountain grades. Luggage space shrinks once all seven seats are filled, so a group traveling with heavy bags should ask about the roof rack option. Automatic transmission is standard on this vehicle, unlike most of the fleet’s smaller cars.',
      },
      hy: {
        title: 'Ընտանեկան Մինիավտոբուս — 7 Տեղանոց',
        summary:
          'Ավտոմատ փոխանցումատուփով 7 տեղանոց մինիավտոբուս, նախատեսված ընտանիքի կամ փոքր խմբի համար, ովքեր ճամփորդում են միասին։',
        description:
          'Այս մինիավտոբուսը տեղավորում է յոթ հոգի՝ երեք իրական շարքով, այլ ոչ թե նեղ երրորդ շարքի նստարանով, իսկ ավտոմատ փոխանցումատուփը այն ավելի հեշտ վարելի է դարձնում նրանց համար, ովքեր լեռնային ուղղահայացքների վրա մեխանիկայով վստահ չեն։ Ուղեբեռի տարածքը փոքրանում է, երբ բոլոր յոթ տեղերը զբաղված են, ուստի ծանր ուղեբեռով ճամփորդող խումբը պետք է հարցնի տանիքի կրիչի տարբերակի մասին։ Ի տարբերություն ավտոպարկի փոքր մեքենաների մեծ մասի, այս մեքենայում ավտոմատ փոխանցումատուփը ստանդարտ է։',
      },
      ru: {
        title: 'Семейный минивэн — 7 мест',
        summary:
          'Минивэн на 7 мест с автоматической коробкой передач, рассчитанный на семью или небольшую группу, путешествующую вместе.',
        description:
          'Этот минивэн вмещает семь человек с тремя полноценными рядами, а не тесной скамьёй третьего ряда, а автоматическая коробка передач делает его более простым в управлении для тех, кто неуверенно чувствует себя с механикой на горных подъёмах. Место для багажа сокращается, когда заняты все семь мест, поэтому группе с тяжёлыми сумками стоит уточнить наличие багажника на крыше. В отличие от большинства машин этого парка, автоматическая коробка здесь стандартна.',
      },
    },
    amenities: ['Air Conditioning'],
    policies: [
      { code: 'smoking_allowed', value: 'false' },
      { code: 'cancellation_policy', value: 'MODERATE' },
    ],
    units: [{ type: 'VEHICLE', label: '7-Seat Minivan', capacity: 2 }],
  },

  // === ATTRACTIONS (Armenia Discovery Guides) ==============================
  {
    partner: 'attractions',
    listingType: 'ATTRACTION',
    categorySlug: 'attractions',
    citySlug: 'yerevan',
    slug: 'sprintj-garni-temple-geghard-monastery-excursion',
    pricingModel: 'PER_PERSON',
    amount: 8000,
    images: ['attractions-1.svg', 'attractions-2.svg'],
    translations: {
      en: {
        title: 'Garni Temple & Geghard Monastery Excursion',
        summary:
          'A half-day guided excursion from Yerevan to the pagan Garni temple and the cave monastery at Geghard.',
        description:
          'This excursion pairs two very different sites within an hour of Yerevan: Garni, the only standing Hellenistic-style colonnaded temple in the former Soviet Union, and Geghard, a monastery partly carved directly into the cliff behind it. The guide covers the temple’s reconstruction history and the church’s UNESCO listing along the way. A stop at Garni Gorge’s basalt column formations, locally called the “Symphony of Stones,” is included.',
      },
      hy: {
        title: 'Գառնի Տաճարի և Գեղարդի Վանքի Էքսկուրսիա',
        summary:
          'Կիսօրյա ուղեկցվող էքսկուրսիա Երևանից դեպի հեթանոսական Գառնի տաճարը և Գեղարդի քարանձավային վանքը։',
        description:
          'Այս էքսկուրսիան համադրում է երկու շատ տարբեր վայրեր՝ Երևանից մեկ ժամվա հեռավորության վրա. Գառնին, նախկին Խորհրդային Միությունում միակ կանգուն հելլենիստական ոճի սյունազարդ տաճարն է, իսկ Գեղարդը՝ վանք, որը մասամբ փորագրված է ուղղակիորեն նրա հետևում գտնվող ժայռի մեջ։ Ուղեկցորդը ճանապարհին ներկայացնում է տաճարի վերականգնման պատմությունը և եկեղեցու ՅՈՒՆԵՍԿՕ-ի ցանկում գրանցվելու փաստը։ Ներառված է կանգառ Գառնիի կիրճի բազալտե սյունային կազմավորումների մոտ, որոնք տեղում կոչվում են «Քարերի սիմֆոնիա»։',
      },
      ru: {
        title: 'Экскурсия к храму Гарни и монастырю Гегард',
        summary:
          'Полудневная экскурсия с гидом из Еревана к языческому храму Гарни и пещерному монастырю Гегард.',
        description:
          'Эта экскурсия объединяет два совершенно разных объекта в часе езды от Еревана: Гарни — единственный сохранившийся на территории бывшего СССР колонный храм эллинистического стиля, и Гегард — монастырь, частично высеченный прямо в скале позади него. По пути гид рассказывает об истории реконструкции храма и о включении церкви в список ЮНЕСКО. Включена остановка у базальтовых колонн ущелья Гарни, которые местные называют «Симфонией камней».',
      },
    },
    amenities: ['Family Friendly'],
    policies: [{ code: 'children_allowed', value: 'true' }],
    units: [
      { type: 'TOUR_DEPARTURE', label: 'Shared Group Departure', capacity: 15 },
    ],
  },
  {
    partner: 'attractions',
    listingType: 'ATTRACTION',
    categorySlug: 'attractions',
    citySlug: 'goris',
    slug: 'sprintj-khndzoresk-cave-village-walk',
    pricingModel: 'PER_PERSON',
    amount: 6000,
    images: ['attractions-3.svg', 'attractions-4.svg'],
    translations: {
      en: {
        title: 'Khndzoresk Cave Village Walk',
        summary:
          'A guided walk through the abandoned cliffside cave village of Old Khndzoresk, crossing its swinging footbridge.',
        description:
          'Old Khndzoresk was inhabited until the mid-20th century, and its hand-carved cave dwellings are still visible cut into the canyon walls on both sides. The walk crosses the long swinging footbridge connecting the two sides of the canyon — not for anyone uneasy with heights — and includes a stop at the small underground Anapat hermitage church. The guide points out which caves were homes, stables, and storage rooms.',
      },
      hy: {
        title: 'Խնձորեսկի Քարանձավային Գյուղի Զբոսանք',
        summary:
          'Ուղեկցվող զբոսանք Հին Խնձորեսկի լքված ժայռափոր քարանձավային գյուղով՝ անցնելով նրա ճոճվող ոտքով կամրջով։',
        description:
          'Հին Խնձորեսկը բնակեցված է եղել մինչև XX դարի կեսը, և նրա ձեռքով փորագրված քարանձավային բնակարանները դեռ երևում են կիրճի երկու կողմերի ժայռերի մեջ։ Զբոսանքն անցնում է երկար ճոճվող ոտքով կամրջով, որը կապում է կիրճի երկու կողմերը (ոչ խորհուրդ է տրվում բարձրությունից վախեցողներին) և ներառում է կանգառ փոքր ստորգետնյա Անապատ մենաստանային եկեղեցու մոտ։ Ուղեկցորդը ցույց է տալիս, թե որ քարանձավներն են եղել տներ, ախոռներ և պահեստներ։',
      },
      ru: {
        title: 'Прогулка по пещерному селу Хндзореск',
        summary:
          'Прогулка с гидом по заброшенному скальному пещерному селу Старый Хндзореск с переходом по подвесному пешеходному мосту.',
        description:
          'Старый Хндзореск был обитаем до середины XX века, и его вырубленные вручную пещерные жилища до сих пор видны в скалах по обе стороны каньона. Прогулка включает переход по длинному подвесному мосту, соединяющему обе стороны каньона (не для тех, кто боится высоты), и остановку у небольшой подземной церкви-скита Анапат. Гид объясняет, какие пещеры были домами, конюшнями и складами.',
      },
    },
    amenities: ['Family Friendly'],
    policies: [{ code: 'children_allowed', value: 'true' }],
    units: [
      { type: 'TOUR_DEPARTURE', label: 'Shared Group Departure', capacity: 10 },
    ],
  },
  {
    partner: 'attractions',
    listingType: 'ATTRACTION',
    categorySlug: 'attractions',
    citySlug: 'yerevan',
    slug: 'sprintj-yerevan-street-art-design-walk',
    pricingModel: 'PER_PERSON',
    amount: 5000,
    images: ['attractions-5.svg', 'attractions-6.svg'],
    translations: {
      en: {
        title: 'Yerevan Street Art & Design Walk',
        summary:
          'A relaxed 2-hour walking route through Yerevan’s murals, Soviet modernist buildings, and small design studios.',
        description:
          'This walk skips the standard monument list in favor of the city’s newer visual layer: large-scale murals in the Kond and Downtown districts, examples of Soviet-era modernist architecture that don’t make most guidebooks, and a couple of small design studios open to visitors along the route. Pace is deliberately unhurried, with plenty of stops to look rather than a march between sights, making it a comfortable fit for teenagers as well as adults.',
      },
      hy: {
        title: 'Երևանի Փողոցային Արվեստի և Դիզայնի Զբոսանք',
        summary:
          'Հանգիստ 2-ժամյա քայլարշավ Երևանի որմնանկարներով, խորհրդային մոդեռնիստական շենքերով և փոքր դիզայն ստուդիաներով։',
        description:
          'Այս զբոսանքը բաց է թողնում ստանդարտ հուշարձանների ցանկը՝ ընտրելով քաղաքի ավելի նոր տեսողական շերտը՝ մեծածավալ որմնանկարներ Կոնդ և կենտրոնական թաղամասերում, խորհրդային ժամանակաշրջանի մոդեռնիստական ճարտարապետության օրինակներ, որոնք չեն մտնում ուղեցույցների մեծ մասում, և մի քանի փոքր դիզայն ստուդիաներ, որոնք երթուղու ընթացքում բաց են այցելուների համար։ Տեմպը միտումնավոր ոչ շտապողական է՝ շատ կանգառներով նայելու համար, այլ ոչ թե տեսարժան վայրերի միջև երթի, ինչը այն հարմար է դարձնում ինչպես դեռահասների, այնպես էլ մեծահասակների համար։',
      },
      ru: {
        title: 'Прогулка по стрит-арту и дизайну Еревана',
        summary:
          'Неспешный 2-часовой пешеходный маршрут по муралам Еревана, советским модернистским зданиям и небольшим дизайн-студиям.',
        description:
          'Эта прогулка пропускает стандартный список памятников в пользу более нового визуального слоя города: масштабные муралы в районах Конд и центре, примеры советской модернистской архитектуры, которые не попадают в большинство путеводителей, и несколько небольших дизайн-студий, открытых для посетителей по маршруту. Темп намеренно неспешный, с остановками, чтобы рассмотреть, а не марш-броском между достопримечательностями, что делает прогулку удобной как для подростков, так и для взрослых.',
      },
    },
    amenities: ['Wheelchair Accessible', 'Family Friendly'],
    policies: [{ code: 'children_allowed', value: 'true' }],
    units: [
      { type: 'TOUR_DEPARTURE', label: 'Shared Group Departure', capacity: 12 },
    ],
  },

  // === ENTERTAINMENT VENUES (Yerevan After Hours) =========================
  {
    partner: 'entertainment',
    listingType: 'ATTRACTION',
    categorySlug: 'entertainment-venues',
    citySlug: 'yerevan',
    slug: 'sprintj-labyrinth-escape-rooms',
    pricingModel: 'PER_PERSON',
    amount: 6000,
    images: ['entertainment-venues-1.svg', 'entertainment-venues-2.svg'],
    translations: {
      en: {
        title: 'Labyrinth Escape Rooms',
        summary:
          'Three themed escape rooms in central Yerevan, built for groups of 2–6 players.',
        description:
          'Labyrinth runs three separate escape rooms — a detective mystery, a heist scenario, and a horror-themed room — each with its own 60-minute session and a live game master watching through the room’s camera feed to give hints if a group gets stuck. Rooms are booked per session rather than per seat, so a group of two pays the same room price as a group of six. The horror room is not recommended for children under 12.',
      },
      hy: {
        title: 'Լաբիրինթոս Խուսափման Սենյակներ',
        summary:
          'Երեք թեմատիկ խուսափման սենյակներ Երևանի կենտրոնում՝ նախատեսված 2-6 խաղացող ունեցող խմբերի համար։',
        description:
          'Լաբիրինթոսն ունի երեք առանձին խուսափման սենյակ՝ դետեկտիվ առեղծված, կողոպուտի սցենար և սարսափ-թեմատիկ սենյակ, յուրաքանչյուրն ունի իր 60-րոպեանոց սեսիան և կենդանի խաղավար, ով սենյակի տեսախցիկով հետևում է և հուշումներ է տալիս, եթե խումբը խրվում է։ Սենյակները ամրագրվում են ըստ սեսիայի, ոչ թե տեղի, ուստի երկուսից բաղկացած խումբը վճարում է նույն գինը, ինչ վեցից բաղկացած խումբը։ Սարսափ սենյակը խորհուրդ չի տրվում 12 տարեկանից փոքր երեխաների համար։',
      },
      ru: {
        title: 'Квест-румы Labyrinth',
        summary:
          'Три тематических квест-рума в центре Еревана для групп от 2 до 6 игроков.',
        description:
          'Labyrinth предлагает три отдельных квест-рума — детективную тайну, сценарий ограбления и комнату в жанре хоррор — каждый с собственной 60-минутной сессией и живым game-мастером, который следит за группой через камеру и даёт подсказки, если игроки застряли. Комнаты бронируются за сессию, а не за место, поэтому группа из двух человек платит столько же, сколько группа из шести. Комната ужасов не рекомендуется детям младше 12 лет.',
      },
    },
    amenities: ['Air Conditioning', 'Parking'],
    policies: [{ code: 'children_allowed', value: 'false' }],
    units: [
      { type: 'TOUR_DEPARTURE', label: 'Escape Room Session', capacity: 6 },
    ],
  },
  {
    partner: 'entertainment',
    listingType: 'ATTRACTION',
    categorySlug: 'entertainment-venues',
    citySlug: 'yerevan',
    slug: 'sprintj-pixeldrift-vr-arena',
    pricingModel: 'PER_HOUR',
    amount: 8000,
    images: ['entertainment-venues-3.svg', 'entertainment-venues-4.svg'],
    translations: {
      en: {
        title: 'PixelDrift VR Arena',
        summary:
          'A free-roam virtual reality arena with wireless headsets, booked by the hour per play area.',
        description:
          'PixelDrift runs a free-roam VR setup rather than seated-headset booths, meaning players walk around a tracked physical space while the headset renders a matching virtual environment — mostly booked for cooperative shooter and puzzle-adventure titles. One booking covers the full play area for up to 4 players for the hour, not per individual headset. Staff run a mandatory 10-minute safety and controls briefing before every session.',
      },
      hy: {
        title: 'ՓիքսելԴրիֆթ VR Ասպարեզ',
        summary:
          'Ազատ տեղաշարժով վիրտուալ իրականության ասպարեզ անլար սաղավարտներով՝ ամրագրվում է ժամով՝ ըստ խաղային տարածքի։',
        description:
          'ՓիքսելԴրիֆթը գործարկում է ազատ տեղաշարժով VR համակարգ՝ նստած-սաղավարտով խցիկների փոխարեն, ինչը նշանակում է, որ խաղացողները քայլում են հետագծվող ֆիզիկական տարածքով, մինչդեռ սաղավարտը ցուցադրում է համապատասխան վիրտուալ միջավայրը, հիմնականում ամրագրվում է համագործակցային հրաձգային և գլուխկոտրուկ-արկածային խաղերի համար։ Մեկ ամրագրումը ծածկում է ամբողջ խաղային տարածքը մինչև 4 խաղացողի համար մեկ ժամով, ոչ թե յուրաքանչյուր սաղավարտի համար առանձին։ Անձնակազմը յուրաքանչյուր սեսիայից առաջ անցկացնում է պարտադիր 10-րոպեանոց անվտանգության և կառավարման հրահանգում։',
      },
      ru: {
        title: 'VR-арена PixelDrift',
        summary:
          'VR-арена со свободным перемещением и беспроводными шлемами, бронируется по часам за игровую зону.',
        description:
          'PixelDrift использует систему VR со свободным перемещением, а не кабинки с сидячим шлемом: игроки перемещаются по отслеживаемому физическому пространству, пока шлем отображает соответствующую виртуальную среду — чаще всего бронируют для кооперативных шутеров и квестов-приключений. Одно бронирование покрывает всю игровую зону на час для до 4 игроков, а не за отдельный шлем. Перед каждой сессией персонал проводит обязательный 10-минутный инструктаж по безопасности и управлению.',
      },
    },
    amenities: ['Air Conditioning', 'Parking'],
    policies: [{ code: 'children_allowed', value: 'true' }],
    units: [{ type: 'TOUR_DEPARTURE', label: 'VR Play Area', capacity: 4 }],
  },
  {
    partner: 'entertainment',
    listingType: 'ATTRACTION',
    categorySlug: 'entertainment-venues',
    citySlug: 'gyumri',
    slug: 'sprintj-ararat-lanes-bowling-arcade',
    pricingModel: 'PER_HOUR',
    amount: 10000,
    images: ['entertainment-venues-5.svg', 'entertainment-venues-6.svg'],
    translations: {
      en: {
        title: 'Ararat Lanes Bowling & Arcade',
        summary:
          'A family bowling alley in Gyumri with six lanes and an attached arcade room.',
        description:
          'Ararat Lanes has six bowling lanes with bumpers available for younger children, plus an arcade room with racing games and a small prize counter that stays open past the alley’s own closing time. Lanes are booked by the hour rather than per game, which works out cheaper for a group of four or more staying through several games. Bowling shoes are included in the lane price; outside food is not permitted in the lane area.',
      },
      hy: {
        title: 'Արարատ Լեյնս Բոուլինգ և Խաղասրահ',
        summary:
          'Ընտանեկան բոուլինգ-ակումբ Գյումրիում՝ վեց ուղիներով և կից խաղասրահով։',
        description:
          'Արարատ Լեյնսն ունի վեց բոուլինգ ուղի՝ փոքր երեխաների համար հասանելի բամպերներով, ինչպես նաև խաղասրահ՝ մրցարշավային խաղերով և փոքրիկ մրցանակների վաճառակետով, որը բաց է մնում ակումբի փակման ժամից հետո։ Ուղիները ամրագրվում են ժամով, ոչ թե ըստ խաղի, ինչը ավելի էժան է դառնում չորս և ավել հոգանոց խմբի համար, ով մնում է մի քանի խաղի ընթացքում։ Բոուլինգի կոշիկները ներառված են ուղու գնի մեջ. արտաքին սնունդը թույլատրված չէ ուղու տարածքում։',
      },
      ru: {
        title: 'Боулинг и аркада Ararat Lanes',
        summary:
          'Семейный боулинг-клуб в Гюмри с шестью дорожками и залом игровых автоматов.',
        description:
          'В Ararat Lanes шесть боулинг-дорожек с бортиками для маленьких детей, а также зал игровых автоматов с гоночными играми и небольшой стойкой призов, которая работает позже времени закрытия самого боулинга. Дорожки бронируются по часам, а не за игру, что выгоднее для компании из четырёх и более человек, играющих несколько партий подряд. Обувь для боулинга включена в стоимость дорожки; свою еду проносить в зону дорожек нельзя.',
      },
    },
    amenities: ['Family Friendly', 'Parking', 'Air Conditioning'],
    policies: [{ code: 'children_allowed', value: 'true' }],
    units: [{ type: 'TOUR_DEPARTURE', label: 'Lane Booking', capacity: 6 }],
  },
];

async function resolveAmenityIds(connection, names) {
  if (names.length === 0) return [];
  const [rows] = await connection.query(
    'SELECT id FROM listing_amenities WHERE name IN (?)',
    [names],
  );
  return rows.map((row) => row.id);
}

async function createUser(connection, ctx, { email, fullName }) {
  const [firstName, ...rest] = fullName.split(' ');
  const lastName = rest.join(' ') || firstName;
  const passwordHash = await argon2.hash(DEMO_PASSWORD);
  const normalizedEmail = email.trim().toLowerCase();
  const [result] = await connection.query(
    `INSERT INTO users
      (email, normalized_email, password_hash, first_name, last_name, status_id,
       is_email_verified, email_verified_at, preferred_language_id, preferred_currency_id)
     VALUES (?, ?, ?, ?, ?, ?, 1, UTC_TIMESTAMP(3), ?, ?)`,
    [
      email,
      normalizedEmail,
      passwordHash,
      firstName,
      lastName,
      ctx.activeStatusId,
      ctx.enLanguageId,
      ctx.amdCurrencyId,
    ],
  );
  const userId = result.insertId;
  await connection.query(
    'INSERT IGNORE INTO role_user (role_id, user_id) VALUES (?, ?)',
    [ctx.customerRoleId, userId],
  );
  return userId;
}

async function createPartner(connection, ctx, spec) {
  const ownerUserId = await createUser(connection, ctx, {
    email: spec.email,
    fullName: spec.displayName,
  });
  const [result] = await connection.query(
    `INSERT INTO partners
      (legal_name, display_name, slug, email, verification_status_id, moderation_status_id, owner_user_id)
     VALUES (?, ?, ?, ?, ?, ?, ?)`,
    [
      spec.legalName,
      spec.displayName,
      spec.slug,
      spec.email,
      ctx.approvedStatusId,
      ctx.approvedStatusId,
      ownerUserId,
    ],
  );
  const partnerId = result.insertId;
  // eslint-disable-next-line no-restricted-syntax -- seeding must run in a stable, readable order
  for (const [localeCode, description] of Object.entries(spec.translations)) {
    // eslint-disable-next-line no-await-in-loop -- sequential by design
    await connection.query(
      'INSERT INTO partner_translations (partner_id, language_id, description) VALUES (?, ?, ?)',
      [partnerId, ctx.languageIds.get(localeCode), description],
    );
  }
  await connection.query(
    'INSERT INTO partner_employees (partner_id, user_id, role_id) VALUES (?, ?, ?)',
    [partnerId, ownerUserId, ctx.ownerRoleId],
  );
  return { partnerId, ownerUserId };
}

async function createFullListing(connection, ctx, spec) {
  const partner = ctx.partnersByKey.get(spec.partner);
  const listingId = await insertListing(connection, {
    partnerId: partner.partnerId,
    ownerUserId: partner.ownerUserId,
    listingTypeId: ctx.listingTypeIds.get(spec.listingType),
    categoryId: ctx.categoryIdBySlug.get(spec.categorySlug),
    citySlug: spec.citySlug,
    slug: spec.slug,
    title: spec.translations.en.title,
    summary: spec.translations.en.summary,
    description: spec.translations.en.description,
    pricingModelId: ctx.pricingModelIds.get(spec.pricingModel),
    amount: spec.amount,
    amdCurrencyId: ctx.amdCurrencyId,
    enLanguageId: ctx.enLanguageId,
    imageTypeId: ctx.imageTypeId,
    completedUploadStatusId: ctx.completedUploadStatusId,
    approvedStatusId: ctx.approvedStatusId,
    publishedListingStatusId: ctx.publishedListingStatusId,
    now: ctx.now,
    imagePaths: spec.images.map(
      (file) => `/assets/images/demo/${spec.categorySlug}/${file}`,
    ),
  });

  await upsertTranslation(connection, listingId, ctx.languageIds.get('hy'), {
    title: spec.translations.hy.title,
    summary: spec.translations.hy.summary,
    description: spec.translations.hy.description,
  });
  await upsertTranslation(connection, listingId, ctx.languageIds.get('ru'), {
    title: spec.translations.ru.title,
    summary: spec.translations.ru.summary,
    description: spec.translations.ru.description,
  });

  const amenityIds = await resolveAmenityIds(connection, spec.amenities);
  if (amenityIds.length > 0) {
    await connection.query(
      'INSERT INTO listing_amenity_listing (listing_id, amenity_id) VALUES ?',
      [amenityIds.map((amenityId) => [listingId, amenityId])],
    );
  }

  // eslint-disable-next-line no-restricted-syntax -- seeding must run in a stable, readable order
  for (const policy of spec.policies) {
    // eslint-disable-next-line no-await-in-loop -- sequential by design
    await insertPolicyValue(connection, listingId, policy);
  }

  // eslint-disable-next-line no-restricted-syntax -- seeding must run in a stable, readable order
  for (const unit of spec.units) {
    // eslint-disable-next-line no-await-in-loop -- sequential by design
    const unitId = await insertBookableUnit(connection, {
      listingId,
      bookableUnitTypeId: ctx.unitTypeIds.get(unit.type),
      capacity: unit.capacity,
      unitLabel: unit.label ?? null,
      ownerUserId: partner.ownerUserId,
      maxGuests: unit.maxGuests ?? null,
      basePriceAmount: unit.basePriceAmount ?? null,
      basePriceCurrencyId: unit.basePriceAmount ? ctx.amdCurrencyId : null,
    });
    // eslint-disable-next-line no-await-in-loop -- sequential by design
    await seedCalendarWindow(connection, {
      unitId,
      capacity: unit.capacity,
      from: ctx.now,
      days: 240,
      availableStatusId: ctx.availableStatusId,
    });
  }

  return listingId;
}

/** One 30-day, already-ACTIVE, already-paid promotion — mirrors the state an Admin reaches via `POST /advertising/admin` + `markPaidNow: true`, written directly since seed scripts write raw SQL rather than call through the HTTP API (this `demo/` family's own established convention). */
async function createTopPromotion(
  connection,
  ctx,
  { placementCode, listingId },
) {
  const [[listing]] = await connection.query(
    'SELECT partner_id FROM listings WHERE id = ?',
    [listingId],
  );
  const [[placementType]] = await connection.query(
    'SELECT id FROM ad_placement_types WHERE code = ?',
    [placementCode],
  );
  const [[product]] = await connection.query(
    `SELECT ap.id, ap.price_amount FROM ad_products ap
     WHERE ap.ad_placement_type_id = ? AND ap.duration_days = 30`,
    [placementType.id],
  );
  const startDate = ctx.now.toISOString().slice(0, 10);
  const endDate = new Date(ctx.now.getTime() + 30 * 24 * 60 * 60 * 1000)
    .toISOString()
    .slice(0, 10);
  const [result] = await connection.query(
    `INSERT INTO advertisements
      (listing_id, partner_id, ad_placement_type_id, ad_product_id, status_id,
       price_snapshot_amount, currency_id, start_date, end_date, display_priority,
       requested_by, approved_by, payment_marked_paid_by, payment_marked_paid_at,
       created_by, updated_by)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 0, ?, ?, ?, UTC_TIMESTAMP(3), ?, ?)`,
    [
      listingId,
      listing.partner_id,
      placementType.id,
      product.id,
      ctx.activeAdvertisementStatusId,
      product.price_amount,
      ctx.amdCurrencyId,
      startDate,
      endDate,
      ctx.adminUserId,
      ctx.adminUserId,
      ctx.adminUserId,
      ctx.adminUserId,
      ctx.adminUserId,
    ],
  );
  return result.insertId;
}

export default async function seedDemoSprintJCatalog(connection) {
  const [
    activeStatusId,
    approvedStatusId,
    customerRoleId,
    ownerRoleId,
    amdCurrencyId,
    imageTypeId,
    completedUploadStatusId,
    publishedListingStatusId,
    availableStatusId,
    activeAdvertisementStatusId,
  ] = await Promise.all([
    getIdByCode(connection, 'user_statuses', 'ACTIVE'),
    getIdByCode(connection, 'moderation_statuses', 'APPROVED'),
    getIdByCode(connection, 'roles', 'CUSTOMER'),
    getIdByCode(connection, 'partner_employee_roles', 'OWNER'),
    getIdByCode(connection, 'currencies', 'AMD'),
    getIdByCode(connection, 'media_types', 'IMAGE'),
    getIdByCode(connection, 'media_upload_statuses', 'COMPLETED'),
    getIdByCode(connection, 'listing_statuses', 'PUBLISHED'),
    getIdByCode(connection, 'availability_statuses', 'AVAILABLE'),
    getIdByCode(connection, 'advertisement_statuses', 'ACTIVE'),
  ]);

  const [languageRows] = await connection.query(
    "SELECT id, code FROM languages WHERE code IN ('en', 'hy', 'ru')",
  );
  const languageIds = new Map(languageRows.map((row) => [row.code, row.id]));
  const enLanguageId = languageIds.get('en');

  // The fixed dev-admin account (`005_dev_accounts.js`, part of the plain
  // `seedAll()` baseline) is the actor of record for the 2 TOP promotions
  // below — mirrors an Admin actually approving/marking-paid a promotion
  // through the real `POST /advertising/admin` flow.
  const [[adminUser]] = await connection.query(
    "SELECT id FROM users WHERE normalized_email = 'admin@travelhub.dev'",
  );
  if (!adminUser) {
    throw new Error(
      'seedDemoSprintJCatalog: dev admin account not found — did seedAll() run first?',
    );
  }
  const adminUserId = adminUser.id;

  const listingTypeIds = await getIdsByCode(connection, 'listing_types', [
    'HOTEL',
    'PROPERTY',
    'RESTAURANT',
    'TOUR',
    'CAR_RENTAL',
    'ATTRACTION',
  ]);
  const unitTypeIds = await getIdsByCode(connection, 'bookable_unit_types', [
    'HOTEL_ROOM',
    'PROPERTY_UNIT',
    'RESTAURANT_TABLE',
    'TOUR_DEPARTURE',
    'VEHICLE',
  ]);
  const pricingModelIds = await getIdsByCode(connection, 'pricing_models', [
    'PER_NIGHT',
    'PER_PERSON',
    'PER_HOUR',
    'PER_DAY',
  ]);

  const categorySlugs = [
    'hotels',
    'apartments',
    'villas',
    'guest-houses',
    'restaurants',
    'tours',
    'car-rentals',
    'attractions',
    'entertainment-venues',
  ];
  const categoryIdBySlug = new Map();
  // eslint-disable-next-line no-restricted-syntax -- seeding must run in a stable, readable order
  for (const slug of categorySlugs) {
    // eslint-disable-next-line no-await-in-loop -- sequential by design
    const [[row]] = await connection.query(
      'SELECT id FROM listing_categories WHERE slug = ?',
      [slug],
    );
    if (!row) {
      throw new Error(
        `seedDemoSprintJCatalog: category "${slug}" not found — did seedAll() run first?`,
      );
    }
    categoryIdBySlug.set(slug, row.id);
  }

  const ctx = {
    activeStatusId,
    approvedStatusId,
    customerRoleId,
    ownerRoleId,
    amdCurrencyId,
    imageTypeId,
    completedUploadStatusId,
    publishedListingStatusId,
    availableStatusId,
    languageIds,
    enLanguageId,
    adminUserId,
    activeAdvertisementStatusId,
    listingTypeIds,
    unitTypeIds,
    pricingModelIds,
    categoryIdBySlug,
    now: new Date(),
  };

  const partnersByKey = new Map();
  // eslint-disable-next-line no-restricted-syntax -- seeding must run in a stable, readable order
  for (const [key, spec] of Object.entries(PARTNERS)) {
    // eslint-disable-next-line no-await-in-loop -- sequential by design
    const partner = await createPartner(connection, ctx, spec);
    partnersByKey.set(key, partner);
  }
  ctx.partnersByKey = partnersByKey;

  const listingIds = [];
  const listingIdBySlug = new Map();
  // eslint-disable-next-line no-restricted-syntax -- seeding must run in a stable, readable order
  for (const spec of LISTINGS) {
    // eslint-disable-next-line no-await-in-loop -- sequential by design
    const listingId = await createFullListing(connection, ctx, spec);
    listingIds.push(listingId);
    listingIdBySlug.set(spec.slug, listingId);
  }

  // A small, intentional set of TOP promotions (spec §37: "a few
  // intentional examples... do not TOP every listing") so the Home
  // Featured section and one category's TOP section have something real
  // to show, proving CATEGORY_TOP stays independent of HOMEPAGE_SECTION —
  // exactly the sequence `entertainmentVenues.test.js` (Sprint I) already
  // proves at the API layer; this seeds the same end state directly so it
  // survives a fresh reset without a manual Admin action.
  const promotionIds = [];
  // eslint-disable-next-line no-restricted-syntax -- seeding must run in a stable, readable order
  for (const promo of [
    {
      placementCode: 'HOMEPAGE_SECTION',
      listingId: listingIdBySlug.get('sprintj-jermuk-spa-resort-hotel'),
    },
    {
      placementCode: 'CATEGORY_TOP',
      listingId: listingIdBySlug.get('sprintj-labyrinth-escape-rooms'),
    },
  ]) {
    // eslint-disable-next-line no-await-in-loop -- sequential by design
    const promotionId = await createTopPromotion(connection, ctx, promo);
    promotionIds.push(promotionId);
  }

  return {
    partnerIds: [...partnersByKey.values()],
    listingIds,
    promotionIds,
  };
}
